name: Build & Sign

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zephyrproject-rtos/ci:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: packt-training

      - name: Setup Zephyr
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: packt-training
          manifest-file-name: west.yml
          toolchains: arm-zephyr-eabi

      - name: Write signing key
        env:
          KEY_PEM: ${{ secrets.MCUBOOT_SIGNING_KEY }}
        run: |
          mkdir -p packt-training/keys
          printf '%s' "$KEY_PEM" > packt-training/keys/my-key.pem
          chmod 600 packt-training/keys/my-key.pem
          # Print the key - just for the training purposes
          cat packt-training/keys/my-key.pem

      - name: Build (production target, signed)
        working-directory: packt-training
        run: |
          # TODO 1 - build
          west build -b training app --sysbuild -d build/prod  --pristine

      - name: Verify signature
        working-directory: packt-training
        run: |
          # TODO 2 - verify (fail the build if signing didn't happen)
          imgtool verify -k keys/my-key.pem build/prod/app/zephyr/zephyr.signed.bin

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ github.sha }}
          path: |
            - zephyr-in-production/build/prod/mcuboot/zephyr/zephyr.bin
            - zephyr-in-production/build/prod/app/zephyr/zephyr.signed.bin
          retention-days: 30
